[package]
name = "PteroCrasher"
version = "1.1.0"
edition = "2024"

[[bin]]
name = "crasher"
path = "src/main.rs"

[dependencies]
rand = "0.9.1"
tokio = { version = "1.45.1", features = ["full"] }
reqwest = {version = "0.12.15", default-features = false, features = ["rustls-tls"]}
url = "2.5.4"